import { Context } from "../types";

export const db: Context["db"] = {
  users: [
    {
      id: "1",
      email: "mehdi@fekih.com",
      name: "Mehdi fkih",
      role: "ADMIN",
    },
    {
      id: "2",
      email: "medamine@gdoura.com",
      name: "Med Amine Gdoura",
      role: "ADMIN",
    },
    {
      id: "3",
      email: "Mahdi@chaabane.com",
      name: "Mahdi Chaabane",
      role: "USER",
    },
    {
      id: "4",
      email: "mehdi@khelil.com",
      name: "Mehdi khelil",
      role: "USER",
    },
    {
      id: "5",
      email: "houssem@sahnoun.com",
      name: "Houssem Sahnoun",
      role: "ADMIN",
    },
  ],
  skills: [
    { id: "1", designation: "HTML" },
    { id: "2", designation: "CSS" },
    { id: "3", designation: "JavaScript" },
    { id: "4", designation: "React" },
    { id: "5", designation: "Node.js" },
    { id: "6", designation: "Python" },
    { id: "7", designation: "SQL" },
  ],
  cvs: [
    {
      id: "1",
      name: "Fake CV 1",
      age: 25,
      job: "Web Developer",
      owner: "1",
    },
    {
      id: "2",
      name: "Fake CV 2",
      age: 28,
      job: "Frontend Developer",
      owner: "2",
    },
    {
      id: "3",
      name: "Fake CV 3",
      age: 30,
      job: "Backend Developer",
      owner: "3",
    },
    {
      id: "4",
      name: "Fake CV 4",
      age: 26,
      job: "Full Stack Developer",
      owner: "4",
    },
    {
      id: "5",
      name: "Fake CV 5",
      age: 29,
      job: "Software Engineer",
      owner: "5",
    },
    {
      id: "6",
      name: "Fake CV 6",
      age: 27,
      job: "Data Scientist",
      owner: "1",
    },
    {
      id: "7",
      name: "Fake CV 7",
      age: 31,
      job: "UI/UX Designer",
      owner: "2",
    },
    {
      id: "8",
      name: "Fake CV 8",
      age: 24,
      job: "Network Engineer",
      owner: "3",
    },
    {
      id: "9",
      name: "Fake CV 9",
      age: 32,
      job: "Project Manager",
      owner: "4",
    },
    {
      id: "10",
      name: "Fake CV 10",
      age: 26,
      job: "System Administrator",
      owner: "5",
    },
  ],
  cvSkills: [
    { cvId: "1", skillId: "1" },
    { cvId: "1", skillId: "3" },
    { cvId: "1", skillId: "4" },
    { cvId: "2", skillId: "2" },
    { cvId: "2", skillId: "3" },
    { cvId: "2", skillId: "4" },
    { cvId: "3", skillId: "5" },
    { cvId: "3", skillId: "6" },
    { cvId: "3", skillId: "7" },
    { cvId: "4", skillId: "1" },
    { cvId: "4", skillId: "2" },
    { cvId: "4", skillId: "3" },
    { cvId: "4", skillId: "4" },
    { cvId: "4", skillId: "5" },
    { cvId: "5", skillId: "3" },
    { cvId: "5", skillId: "4" },
    { cvId: "5", skillId: "5" },
    { cvId: "5", skillId: "6" },
    { cvId: "6", skillId: "6" },
    { cvId: "6", skillId: "7" },
    { cvId: "7", skillId: "1" },
    { cvId: "7", skillId: "2" },
    { cvId: "8", skillId: "3" },
    { cvId: "8", skillId: "4" },
    { cvId: "8", skillId: "5" },
    { cvId: "9", skillId: "1" },
    { cvId: "9", skillId: "2" },
    { cvId: "9", skillId: "5" },
    { cvId: "9", skillId: "6" },
    { cvId: "10", skillId: "3" },
    { cvId: "10", skillId: "4" },
    { cvId: "10", skillId: "7" },
  ],
};
